### ISSUE TITLE
Cannot install v0.1.0 on laravel 5.2.20

### ISSUE THREAD

**Issue by ibrahimlawal** [MalikAbiola/paystack-php-lib#10]
Hi Malik,

Great library, easy to use. Was hoping to do a sample app with it. but having issues with requiring the library on laravel. Details of the problem >

> Problem 1
>     - Installation request for mabiola/paystack-php-lib ^0.1.0 -> satisfiable by mabiola/paystack-php-lib[0.1.0].
>     - Conclusion: remove vlucas/phpdotenv v2.2.0
>     - Conclusion: don't install vlucas/phpdotenv v2.2.0
>     - mabiola/paystack-php-lib 0.1.0 requires vlucas/phpdotenv ~1.0 -> satisfiable by vlucas/phpdotenv[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, v1.0.8, v1.0.9, v1.1.0, v1.1.1].
>     - Can only install one of: vlucas/phpdotenv[1.0.0, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.1, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.2, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.3, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.4, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.5, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[1.0.6, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[v1.0.8, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[v1.0.9, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[v1.1.0, v2.2.0].
>     - Can only install one of: vlucas/phpdotenv[v1.1.1, v2.2.0].
>     - Installation request for vlucas/phpdotenv == 2.2.0.0 -> satisfiable by vlucas/phpdotenv[v2.2.0].

**Comment by MalikAbiola** [comment]
Thank you for spotting this. 

Issue has been resolved. And a patch of the library released. 

Please do a composer update to update dependencies. 

Fixed in #11
