### ISSUE TITLE
Specifying the Secret Key

### ISSUE THREAD

**Issue by crobytech** [MalikAbiola/paystack-php-lib#13]
Hi, the code only allows the specification of the secret key via the .env file. I think that is a bit too strict. The user might be storing the key in a database or some other source. Perhaps their should be an option to let the user specify the keys.

Would be happy to do a pull request for this.

**Comment by MalikAbiola** [comment]
Personally, I prefer saving constants that could switch based on the environment or some other condition in an .env, and I don't get why you would want to hit your db every time u need to retrieve your key as that isn't good for performance, and what other source would you try if not a .env?

All i'm saying is, I'll need a lil bit more convincing.

But while thinking of this, I actually thought of a cool way to implement something like this. But give me some more reasons why you wouldn't want to use the "too strict" .env file and suggest other practical ways you'd implement this. and we'll see how we can work on that PR.

**Comment by crobytech** [comment]
Good point at performance. I had not quite thought about it that way. 

I was coming from an access_token, refresh_token, expire time background where the values would change frequently and writing each time to a file seemed more troublesome than writing to a db. 

The other argument I have left is that it encourages 'freedom' so to speak, while it's cool to enforce certain practices, it's usually better in my opinion to let the user decide albeit with a hint as to the preferred method.

**Comment by MalikAbiola** [comment]
:smile: 

The real point of saving them in .env is cos they mostly never change and once loaded, are globally available in your $_ENV. 

Also, while i understand your freedom argument, i feel its best to teach users(developers) best practices when they use something they didn't write, so they can pick up one or two new ideas from there.

**Comment by crobytech** [comment]
Fair enough
